# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
cache: packages

matrix:
  include:
    - os: linux
      r: release
      env:
        - R_CODECOV=true
    - os: linux
      r: devel
    - os: linux
      r: oldrel

warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
- if [[ "${R_CODECOV}" ]]; then Rscript -e 'covr::codecov()'; fi
